apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: kafka.binding
spec:
  type: bindings.kafka
  version: v1
  metadata:
  - name: brokers
    value: "dapr-kafka-headless.kafka.svc.cluster.local:9092"
  - name: topics
    value: neworder
  - name: consumerGroup
    value: group1
  - name: publishTopic
    value: neworder
  - name: authRequired
    value: false
